# Generated by Django 5.0.4 on 2024-04-25 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
